// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTy_37jfiFHdmF9Ggjm4zrWwQLoO6bPJk',
    appId: '1:503349493628:web:a8035f4c0feec188be6ef9',
    messagingSenderId: '503349493628',
    projectId: 'tictactoe-9c4bd',
    authDomain: 'tictactoe-9c4bd.firebaseapp.com',
    storageBucket: 'tictactoe-9c4bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzeP8LThbQEoGTGkuOHLWBh7CYXAgA2Gs',
    appId: '1:503349493628:android:4360889439a07691be6ef9',
    messagingSenderId: '503349493628',
    projectId: 'tictactoe-9c4bd',
    storageBucket: 'tictactoe-9c4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjkw0GZ6dnx34I8HR6qQ7Y5VKbZfZhq4',
    appId: '1:503349493628:ios:1104cacff358ce16be6ef9',
    messagingSenderId: '503349493628',
    projectId: 'tictactoe-9c4bd',
    storageBucket: 'tictactoe-9c4bd.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjkw0GZ6dnx34I8HR6qQ7Y5VKbZfZhq4',
    appId: '1:503349493628:ios:4df4a9d568809392be6ef9',
    messagingSenderId: '503349493628',
    projectId: 'tictactoe-9c4bd',
    storageBucket: 'tictactoe-9c4bd.appspot.com',
    iosBundleId: 'com.example.tictactoe.RunnerTests',
  );
}
